import Head from "next/head"

export default function Layout({title, children}){
    return(
        <>
            <Head>
                <title>{title ? title + '- Amazona' : 'Amazona'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <header>
                    <nav>
                        This is navbar
                    </nav>
                </header>
                <main>{children}</main>
                <footer>footer</footer>

            </div>
        </>
    )
}