import Head from "next/head"
import Link from "next/link"

export default function Layout({title, children}){
    return(
        <>
            <Head>
                <title>{title ? title + '- Amazona' : 'Amazona'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col justify-between'>
                <header>
                    <nav className="flex h-12 justify-between shadow-md items-center px-4">
                        <Link href='/' legacyBehavior>
                            <a className="text-lg font-bold">Amazona</a>
                        </Link>
                        <div>
                            <Link href='/cart' legacyBehavior>
                                <a className="p-2">Cart</a>
                            </Link>
                            <Link href='/login' legacyBehavior>
                                <a className="p-2">Login</a>
                            </Link>
                        </div>
                    </nav>
                </header>
                <main className="container m-auto mt-4 px-4">{children}</main>
                <footer className="flex h-10 justify-center items-center shadow-inner">Copyright © 2022 Amazona</footer>

            </div>
        </>
    )
}